raccoongang/credentials

credentials/apps/verifiable_credentials/apps.py, credentials/apps/verifiable_credentials/settings.py, credentials/settings/devstack.py
=> feat: [OeX_Cred-310] add conditional VC configuration

credentials/apps/verifiable_credentials/rest_api/urls.py, credentials/apps/verifiable_credentials/rest_api/v1/serializers.py, credentials/apps/verifiable_credentials/rest_api/v1/tests/test_serializers.py, credentials/apps/verifiable_credentials/rest_api/v1/tests/test_views.py, credentials/apps/verifiable_credentials/rest_api/v1/urls.py, credentials/apps/verifiable_credentials/rest_api/v1/views.py, credentials/apps/verifiable_credentials/tests/test_utils.py, credentials/apps/verifiable_credentials/urls.py, credentials/apps/verifiable_credentials/utils.py, credentials/settings/test.py, credentials/urls.py
=> feat: [OeX_Cred-206] add program certificates list endpoint

credentials/apps/verifiable_credentials/rest_api/v1/tests/test_views.py, credentials/apps/verifiable_credentials/rest_api/v1/urls.py, credentials/apps/verifiable_credentials/rest_api/v1/views.py
=> feat: [OeX_Cred-290, OeX_Cred-321, OeX_Cred-284] add qrcode, wallet and deeplink api views

credentials/apps/verifiable_credentials/admin.py, credentials/apps/verifiable_credentials/apps.py, credentials/apps/verifiable_credentials/settings.py, credentials/apps/verifiable_credentials/storages.py, credentials/apps/verifiable_credentials/toggles.py, credentials/apps/verifiable_credentials/wallets.py, credentials/settings/base.py, credentials/settings/devstack.py, credentials/urls.py
=> refactor(settings): [OeX_Cred-425] incapsulate VC settings

credentials/apps/verifiable_credentials/composition/__init__.py, credentials/apps/verifiable_credentials/composition/open_badges.py, credentials/apps/verifiable_credentials/composition/verifiable_credentials.py, credentials/apps/verifiable_credentials/issuance.py, credentials/apps/verifiable_credentials/models.py, credentials/apps/verifiable_credentials/rest_api/v1/views.py, credentials/apps/verifiable_credentials/settings.py, credentials/apps/verifiable_credentials/storages/__init__.py, credentials/apps/verifiable_credentials/utils.py, requirements/all.txt, requirements/base.in, requirements/base.txt, requirements/common_constraints.txt, requirements/dev.txt, requirements/docs.txt, requirements/pip.txt, requirements/production.txt, requirements/test.in, requirements/test.txt, requirements/translations.txt
=> feat: [OeX_Cred-381] add proof

credentials/apps/verifiable_credentials/composition/open_badges.py
=> feat: [OeX_Cred-603] compose open badges data model

credentials/apps/verifiable_credentials/apps.py, credentials/apps/verifiable_credentials/checks.py, credentials/apps/verifiable_credentials/toggles.py, credentials/settings/private.py.example, credentials/settings/test.py
=> feat: [OeX_Cred-572] add vc settings consistency checks

credentials/apps/verifiable_credentials/composition/schemas.py, credentials/apps/verifiable_credentials/composition/status_list.py, credentials/settings/base.py, requirements/all.txt, requirements/base.in, requirements/base.txt, requirements/common_constraints.txt, requirements/dev.txt, requirements/docs.txt, requirements/production.txt, requirements/test.txt, requirements/translations.txt
=> refactor: [OeX_Creds-711] cleanup

credentials/apps/verifiable_credentials/issuance/__init__.py, credentials/apps/verifiable_credentials/issuance/main.py, credentials/apps/verifiable_credentials/issuance/utils.py, credentials/apps/verifiable_credentials/management/commands/generate_issuer_credentials.py, credentials/apps/verifiable_credentials/management/commands/generate_status_list.py, credentials/apps/verifiable_credentials/management/commands/remove_issuance_configuration.py, credentials/apps/verifiable_credentials/permissions.py
=> chore: [OeX_Cred-711] refinements

credentials/apps/verifiable_credentials/composition/tests/test_verifiable_credentials.py, credentials/apps/verifiable_credentials/issuance/tests/test_init.py, credentials/apps/verifiable_credentials/issuance/tests/test_main.py, credentials/apps/verifiable_credentials/issuance/tests/test_renderers.py, credentials/apps/verifiable_credentials/issuance/tests/test_status_list.py, credentials/apps/verifiable_credentials/issuance/tests/test_utils.py, credentials/apps/verifiable_credentials/management/commands/tests/test_create_default_issuer.py, credentials/apps/verifiable_credentials/management/commands/tests/test_generate_issuer_credentials.py, credentials/apps/verifiable_credentials/management/commands/tests/test_generate_status_list.py, credentials/apps/verifiable_credentials/management/commands/tests/test_remove_issuance_configuration.py, credentials/apps/verifiable_credentials/tests/test_checks.py, credentials/apps/verifiable_credentials/tests/test_permissions.py
=> feat: [OeX_Cred-772] write unit-tests to fill coverage

credentials/apps/verifiable_credentials/composition/tests/test_open_badges.py, credentials/apps/verifiable_credentials/composition/tests/test_status_list.py, credentials/apps/verifiable_credentials/rest_api/v1/tests/test_views.py, credentials/apps/verifiable_credentials/storages/tests/test_utils.py, credentials/apps/verifiable_credentials/tests/test_signals.py
=> test: [OeX_Cred-772] more unit-tests

credentials/apps/badges/admin.py, credentials/apps/badges/apps.py, credentials/apps/badges/checks.py, credentials/apps/badges/distribution/credly/credly_badges/LICENSE.txt, credentials/apps/badges/distribution/credly/credly_badges/__init__.py, credentials/apps/badges/distribution/credly/credly_badges/apps.py, credentials/apps/badges/distribution/credly/credly_badges/requirements/base.in, credentials/apps/badges/distribution/credly/credly_badges/requirements/constraints.txt, credentials/apps/badges/distribution/credly/credly_badges/settings/base.py, credentials/apps/badges/distribution/credly/credly_badges/settings/production.py, credentials/apps/badges/distribution/credly/credly_badges/settings/test.py, credentials/apps/badges/distribution/credly/credly_badges/urls.py, credentials/apps/badges/distribution/credly/pyproject.toml, credentials/apps/badges/models.py, credentials/apps/badges/settings/base.py, credentials/apps/badges/settings/production.py, credentials/apps/badges/settings/test.py, credentials/apps/badges/signals.py, credentials/apps/badges/toggles.py, credentials/apps/badges/urls.py, credentials/settings/base.py, pyproject.toml, requirements/all.txt, requirements/base.in, requirements/base.txt, requirements/dev.txt, requirements/docs.txt, requirements/production.txt, requirements/test.txt, requirements/translations.txt
https://youtrack.raccoongang.com/issue/ACI-209
=> feat: [ACI-209] init new badges app

credentials/apps/badges/admin.py, credentials/apps/badges/apps.py, credentials/apps/badges/toggles.py, credentials/apps/badges/urls.py
https://youtrack.raccoongang.com/issue/ACI-222
=> feat: [ACI-222] feature flag for badges

credentials/apps/badges/distribution/credly/credly_badges/data.py, credentials/apps/badges/distribution/credly/credly_badges/exceptions.py, credentials/apps/badges/distribution/credly/credly_badges/rest_api.py, credentials/apps/badges/distribution/credly/credly_badges/settings/base.py
- https://youtrack.raccoongang.com/issue/ACI-294
- https://youtrack.raccoongang.com/issue/ACI-300
- https://youtrack.raccoongang.com/issue/ACI-306
- https://youtrack.raccoongang.com/issue/ACI-312
- https://youtrack.raccoongang.com/issue/ACI-318
=> feat: [ACI-294] implement credly api client

credentials/apps/badges/distribution/credly/credly_badges/__init__.py, credentials/apps/badges/distribution/credly/credly_badges/admin.py, credentials/apps/badges/distribution/credly/credly_badges/api_client.py, credentials/apps/badges/distribution/credly/credly_badges/apps.py, credentials/apps/badges/distribution/credly/credly_badges/data.py, credentials/apps/badges/distribution/credly/credly_badges/forms.py, credentials/apps/badges/distribution/credly/credly_badges/management/commands/sync_organization_badge_templates.py, credentials/apps/badges/distribution/credly/credly_badges/rest_api.py, credentials/apps/badges/distribution/credly/credly_badges/urls.py, credentials/apps/badges/distribution/credly/credly_badges/utils.py
=> feat: [ACI-387, ACI-393] badge templates synchronization

credentials/apps/badges/distribution/credly/credly_badges/admin.py, credentials/apps/badges/distribution/credly/credly_badges/api_client.py, credentials/apps/badges/distribution/credly/credly_badges/forms.py, credentials/apps/badges/distribution/credly/credly_badges/models.py
This allows Credly Organization details backfilling during the validation process.
=> feat: [ACI-269] auto-fill Credly Organization details

credentials/apps/badges/apps.py, credentials/apps/badges/signals/handlers.py, credentials/apps/badges/utils.py, credentials/settings/base.py
https://youtrack.raccoongang.com/issue/ACI-448/Events-subscription-Public-signals-generic-handler
=> feat: [ACI-448] events subscription, generic handler

credentials/apps/badges/signals/handlers.py
ping-pong
https://youtrack.raccoongang.com/issue/ACI-351/Dumb-echo-handler
=> feat: [ACI-351] dumb echo handler

credentials/apps/badges/distribution/credly/credly_badges/data.py, credentials/apps/badges/distribution/credly/credly_badges/rest_api.py
https://youtrack.raccoongang.com/issue/ACI-479/Fix-Credly-webhook-event-processing
=> fix: [ACI-479] refactor data for webhook

credentials/settings/base.py
https://youtrack.raccoongang.com/issue/ACI-548/Add-badging-events-to-badge-life-cycle-event-bus-topic
=> feat: [ACI-548] update badges event bus config

credentials/settings/base.py
[ACI-585](https://youtrack.raccoongang.com/issue/ACI-585) Credentials event bus consumer issue
=> fix: [ACI-585] Credentials event bus consumer issue

credentials/apps/badges/signals/handlers.py
[ACI-513](https://youtrack.raccoongang.com/issue/ACI-513) Emit CCX course PASSING status
[ACI-519](https://youtrack.raccoongang.com/issue/ACI-519) Emit CCX course FAILING status
=> feat: [ACI-513, ACI-519] Emit CCX course FAILING/PASSING status

credentials/apps/badges/credly/api_client.py, credentials/settings/base.py
Fixes Credly API badges configuration.
=> fix: Credly API configuration

credentials/apps/badges/credly/api_client.py, credentials/apps/badges/credly/webhooks.py, credentials/apps/badges/urls.py, credentials/urls.py
Urlconf fixes
Credly webhook fixes
DB constraints fixes
=> fix: [ACI-814] urlconf fixes

credentials/apps/badges/models.py, credentials/apps/badges/tests/test_models.py
[ACI-851](https://youtrack.raccoongang.com/issue/ACI-851)
=> feat: [ACI-851] implement requirement fulfillment check func

credentials/apps/badges/models.py, credentials/apps/badges/services/awarding.py, credentials/apps/badges/tests/test_issuers.py, credentials/apps/badges/tests/test_models.py, credentials/apps/badges/tests/test_services.py, credentials/apps/badges/tests/test_signals.py
[ACI-852](https://youtrack.raccoongang.com/issue/ACI-852) Data rules application
[ACI-897](https://youtrack.raccoongang.com/issue/ACI-897) Process requirements
=> feat: [ACI-852] Data rules application

credentials/apps/badges/admin_forms.py, credentials/apps/badges/models.py
[ACI-902](https://youtrack.raccoongang.com/issue/ACI-902) Revise the active badge template configuration update
merge after: https://github.com/raccoongang/credentials/pull/120
=> feat: [ACI-902] Revise the active badge template configuration update

credentials/apps/badges/admin.py, credentials/apps/badges/admin_forms.py, credentials/apps/badges/models.py
[ACI-902](https://youtrack.raccoongang.com/issue/ACI-902) Revise the active badge template configuration update
=> fix: [ACI-902] fix badge template deactivation

credentials/apps/badges/admin.py, credentials/apps/badges/admin_forms.py, credentials/apps/badges/models.py, credentials/apps/badges/tests/test_models.py
[ACI-871](https://youtrack.raccoongang.com/issue/ACI-871) Process grouped requirements
=> feat: [ACI-871] Process grouped requirements

credentials/apps/badges/admin.py
=> feat: add active badge templates changing warning

credentials/apps/badges/base_api_client.py, credentials/apps/badges/credly/api_client.py, credentials/apps/badges/exceptions.py
=> refactor: [AXM-1220] make base api client for badges

credentials/apps/badges/accredible/utils.py
Description: Fix wrong Accredible variable naming.
=> fix: fix wrong naming

credentials/apps/badges/admin.py
=> fix: [AXM-1302] fix accredible redirecting on rule save

credentials/apps/badges/issuers.py, credentials/apps/badges/models.py
=> feat: [AXM-1303] remove changing state after revocation

docs/verifiable_credentials/components.rst, docs/verifiable_credentials/usage.rst
=> docs: [AXM-1190] verifiable credentials docs

credentials/apps/badges/admin.py
=> fix: [AXM-1302] redirect to accredible group when save penalty
